Add `python-utils` package
espanso/hub pull request #102
Opened 2024-02-27 19:09 UTC by kchenTTP

Some shortcuts to reduce the amount of boilerplate code for python scripts.

2024-05-07 11:04 UTC, smeech requested changes
Three brief snippets for adding Python boilerplate.
All simple text expansions with no `cmd`, `script`, `shell` or risky code.
Safe to merge after the author, or we, remove the `force_clipboard: true` items.

2024-06-22 01:03 UTC, kchenTTP commented on packages/python-utils/0.1.0/package.yml
> +    force_clipboard: true
I've removed `force_clipboard: true` for all the triggers. Let me know if you have any more suggestions.

2024-06-22 01:06 UTC, kchenTTP commented
I've also added more triggers on a whim. Please also review those and let me know if there's anything I need to fix. Sorry about that.

2024-06-22 10:30 UTC, smeech approved these changes

2024-06-22 10:36 UTC, smeech commented
Excellent! Thank you.

2024-06-22 10:36 UTC, merged