Add sitelen-pona package
espanso/hub pull request #113
Opened 2024-05-06 06:19 UTC by neroist

Added package for typing sitelen pona (toki pona's main writing system) via UCSUR.

If you're wondering the language at the end of the readme is toki pona, and what I wrote translates to about:
> Using this tool, you can write sitelen pona with Espanso. Communicate/talk well and write well!

2024-05-07 14:40 UTC, smeech requested changes
Simple text replacement package. As it uses a lot of common single-character triggers without prefix or suffix, it won't be for everybody, but I can see it might fit within an app-specific config.
A lot of characters not readable on GitHub, but I fed package.yml to https://www.kreativekorp.com/software/fonts/sitelenselikiwen/ to see how they appear.
No `cmd`, `shell`, `script` or apparently risky code.
The README.md could be more helpful.
Needs some tags and could safely be merged.

2024-05-07 14:40 UTC, smeech commented on packages/sitelen-pona/0.1.0/_manifest.yml
> +author: niko
This needs some `tags:`. See [espanso hub](https://hub.espanso.org/search) for examples.

2024-05-07 21:23 UTC, neroist commented
Thank you for the review! I'll make some changes

2024-05-07 21:56 UTC, smeech approved these changes

2024-05-07 21:57 UTC, smeech commented
Thank you. Just awaiting someone else to review the package and I think i can be merged.

2024-05-07 22:29 UTC, rbstrachan approved these changes
I don't think the README is a problem given that anyone who would want to use this package will already be familiar with Toki Pona.

The changes look good to me!

2024-05-07 22:31 UTC, smeech commented
That took me down a rabbit hole - via a YouTube video, and onto the ma pona pi toki pona Discord server!

2024-05-07 22:40 UTC, smeech commented
> I don't think the README is a problem given that anyone who would want to use this package will already be familiar with Toki Pona.
> 
> The changes look good to me!

Yes, it was a minor point.

2024-05-07 23:12 UTC, neroist commented
Regarding the readme, I think it would be helpful to list how many and what words are supported by the package, as well as how to use it (as it doesn't use any prefix or suffix, but is intended to be used with Espanso's toggle key feature).

2024-05-08 09:35 UTC, smeech commented
The tags I was thinking of included "symbols", "languages", "letters", "writing", "characters", "communication" etc..
They'd place the package in those filtered lists in https://hub.espanso.org/search, and make it easier for interested users to find.
I'll leave it to @neroist to choose some or all.

Having taken a trip down the rabbit hole! the README.md could interest people browsing the packages and encourage them to take the same journey. I can see there is an expanding toki pona community. You don't need to go as far as the one for [github-emojis-latest](https://github.com/espanso/hub/blob/230c0e92b7906e3dfbf2c055c5173759edb5c757/packages/github-emojis-latest/1.0.0/README.md)!

2024-05-08 13:09 UTC, smeech commented
I think adding the tags I suggested would be helpful to hub users. We could do that, but yes.

2024-05-08 15:13 UTC, neroist commented
I added the tags :) I think I'll write a README.tok.md and I'll be done (or can there only be one readme?)

2024-05-08 15:28 UTC, merged

2024-05-08 15:31 UTC, AucaCoyan commented
It's a valid question, in the instant I was writing this comment smeech merged it 💯 
We can test having 2 readmes with this pkg. Could you submit another PR adding a readme to this package? no need to add a new version.
We merge it and then we check the website and if it works as expected

2024-05-08 15:33 UTC, smeech commented
I've merged the package.
I think there should only be one README.md.
If you want to update it, we can pull it in quite quickly.
I'm not sure how long it takes for Espanso Hub to pick up the changes,

2024-05-08 15:35 UTC, smeech commented
The Hub website uses README.md, so I think we should stick to one file.

2024-05-08 15:36 UTC, smeech commented
It's in: https://hub.espanso.org/sitelen-pona

2024-05-08 16:33 UTC, AucaCoyan commented
Yeah, on the webpage it will load only one readme, but I'm wondering if you donwload the package with `espanso install sitelen-pona`, does that download the two readmes? it should