feat: Add `expand-contractions` package
espanso/hub pull request #95
Opened 2024-02-09 19:46 UTC by lewisblackburn

This expands contractions e.g. `aren't` → `are not` . 

This is useful for when writing essays, as professional writing often requires a more formal and precise language style, eliminating contractions contributes to a more polished and academic tone.

2024-05-06 22:08 UTC, smeech requested changes
A nice, straightforward package of simple expansions.
No `cmd`, `script`, `shell` or malicious code.
Both `README.md` and `package.yml` would benefit from removing duplicates, and, ideally, sorting into alphabetical order. Let me know if you need any help.
Then it will be safe to merge.

2024-05-06 22:08 UTC, smeech commented on packages/expand-contractions-en/0.1.0/README.md
Many duplicate lines - if you sort them in an editor, you can remove them. Sorting them would look better, too!

2024-05-06 22:08 UTC, smeech commented on packages/expand-contractions-en/0.1.0/package.yml
A number of duplicate expansions. If you can sort these, it'll make it easier for users to comment out any they don't want to use.

2024-09-12 08:59 UTC, lewisblackburn commented on packages/expand-contractions-en/0.1.0/package.yml
Thanks for the feedback! I've made the requested changes:

    Standardized and alphabetized the contraction-to-expansion mappings in the markdown table.
    Removed duplicate entries.
    Added any missing contractions.
    Reformatted the table in the README.md

Let me know if there's anything else you'd like to see updated!

I am going to create a new PR as I can't commit to this one.

2024-09-12 09:38 UTC, smeech commented
I presume you're still working on this - just to let you know I am keeping an eye on it.

2024-09-13 13:29 UTC, lewisblackburn commented
I think everything should be ready to go now, I'd be happy make any more changes. I apologise if there are any mistakes as I am still learning how to use GitHub 😅

2024-09-13 16:29 UTC, smeech commented
I've lost track of the `_manifest.yml` and `README.md` files.

Don't worry - I've learned a lot in the last few months!

2024-09-14 09:43 UTC, smeech commented
Thank you - we're getting there!

Would you kindly:
- Rename the package folder to `/0.1.0/expand-contractions-en` as in your original PR, and in `_manifest.yml`, adding a version subfolder
- Add a `homepage:` parameter to `_manifest.yml` even if the value is just something like: https://github.com/lewisblackburn/hub/tree/main/packages/expand-contractions-en (renamed as above), or https://github.com/lewisblackburn/hub
- Change the installation instructions in `README.md` to download from the Hub, i.e. match those in the [docs](https://espanso.org/docs/packages/basics/)

please?

2024-09-14 13:35 UTC, lewisblackburn commented
Yes of course no worries, I will do that ASAP. Thanks for your patience.

2024-09-14 16:16 UTC, smeech approved these changes

2024-09-14 16:23 UTC, smeech commented
I'm afraid you omitted a period in `/0.1.0/` so it's reading `/0.10/`.

Can you remove the old folder and contents (without the version number), please? While I could delete the files, I might not be able to remove their folder, which may cause problems.

2024-09-14 16:38 UTC, lewisblackburn commented
Oh okay sorry about that, one second

2024-09-14 16:42 UTC, lewisblackburn commented
Should I add the correct folder back?

2024-09-14 16:45 UTC, smeech commented
You may have removed the wrong one. All I can see now in the file-list is the folder and files _without_ the version number.

2024-09-14 17:18 UTC, smeech commented
We're now back to two folders, both named `/espanso-contractions-en/0.1.0/`, I'm afraid. We just need one.

2024-09-14 17:25 UTC, smeech commented
The folder needs the package name: `expand-contractions-en`, as in `_manifest.yml`. Sorry - I should have spotted that earlier.

2024-09-14 17:31 UTC, lewisblackburn commented
I think that should have fixed it

2024-09-14 17:47 UTC, merged

2024-09-14 17:54 UTC, smeech commented
Thank you. I've gone ahead with the merge. The package can be found at https://hub.espanso.org/expand-contractions-en. `espanso install expand-contractions-en` works.

Well done!